Add a way to set custom patterns
macklinu/danger-plugin-no-test-shortcuts pull request #2
Opened 2017-05-03 22:22 UTC by deecewan

If your testing framework doesn't use the same format, or, with Ava for example, you import the `test` function with a different name, none of the checks will work.

This allows people to add (only additional) patterns to be checked, too.

2017-05-04 15:09 UTC, macklinu requested changes
Thanks for contributing! ❤️ 

I see what you mean about importing Ava under a different name, as well as not following the `.skip()` pattern as straightforward as other test frameworks, like in [this doc](https://github.com/avajs/ava#chaining-test-modifiers). They also support [`test.todo()`](https://github.com/avajs/ava#test-placeholders-todo), which might also be a custom skip pattern.

A couple other changes, and this PR should be good to merge for v1.3.0.

---

Please update `index.d.ts` with updated TypeScript types, now that this plugin function takes the `patterns` object. This can be added to the `Config` interface:

```ts
patterns?: {
  only?: string[]
  skip?: string[]
}
```

And please add the usage of `noTestShortcuts` with the `patterns` option to `src/__tests__/test.ts` (following the pattern in the file to call `noTestShortcuts()`) to test that the TypeScript type works as expected. 👍 

Thank you!

2017-05-04 15:09 UTC, macklinu commented on src/index.js
> +    const onlyPatternsResult = patterns.only && patterns.only.length > 0
I believe we can use [`Array.prototype.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some?v=control) to achieve the same idea here:

```js
const onlyPatternsResult  = (patterns.only || []).some(pattern => content.includes(pattern))
```

Also, writing `(patterns.only || [])` will ensure we are always calling `.some()` on a defined array, which is effectively what are you expressing with `patterns.only && patterns.only.length > 0`.

2017-05-04 15:09 UTC, macklinu commented on src/index.js
> +        const skipPatternsResult = patterns.skip && patterns.skip.length > 0
Similar comment as above for using `Array.prototype.some()`:

```js
const skipPatternsResult  = (patterns.skip || []).some(pattern => content.includes(pattern))
```

2017-05-04 15:10 UTC, macklinu commented
Also, this is a good case for getting a Dangerfile up and running in this repo to say "I see you've changed the API - please make sure the TypeScript types and tests are up-to-date". 😃

2017-05-04 22:13 UTC, deecewan commented on src/index.js
> +    const onlyPatternsResult = patterns.only && patterns.only.length > 0
yeah, wow. that is a much better idea.

2017-05-04 22:41 UTC, deecewan commented
Thanks for the feedback.  I made the changes, and also tacked on a little more.

With custom patterns, people may not necessarily know what they're looking for. So I've included the pattern that matched in the error message.

2017-05-05 12:02 UTC, macklinu approved these changes

2017-05-05 12:02 UTC, macklinu commented
That's an awesome idea, thank you!

2017-05-05 12:04 UTC, merged